### PR TITLE
Provide URL name.

### PR DESCRIPTION
**Pull request by jnns**
Make django-documentation's URL resolvable by adding a name.

### CODE REVIEW

**Comment by kenju254** [comment]
@Narsil could you merge this please so that we can have some nice documented and stable module for this.

**Comment by IanLee1521** [comment]
:+1: I was about to propose the same thing.

**Comment by kenju254** [comment]
@IanLee1521 yep.. I too was waiting for this as well.

**Comment by Narsil** [comment]
Sorry, I was not too present on github recently

**Comment by kenju254** [comment]
@Narsil thanks for this..

**Pull request merged**
